### ISSUE TITLE
在api12上无法运行，编译报错！

### ISSUE THREAD

**Issue by hfkai** [hx1997/ark-bytecode-010editor-template#2]

**Comment by hx1997** [comment]
感谢反馈，预计这周末看一下

**Comment by hfkai** [comment]
你好，看得怎样了

**Comment by hx1997** [comment]
因为方舟字节码 12.0.1.0 进行了一次不向下兼容的改动，所以旧版不能用了。已经更新 12.0.1.0 以上的模板，可以试下
https://github.com/hx1997/ark-bytecode-010editor-template/blob/main/abc12.bt

**Comment by hx1997** [comment]
这个 issue 就关了，有问题可以再开。另外可以关注下下面两个项目，他们更新得比我快。
https://github.com/Yricky/abcde
https://github.com/MartinKayJr/abcde-android

**Comment by hfkai** [comment]
大佬好，现在是不会报错了，但是我要怎样才能看到反编译后的代码？第一次玩010Editor，不太熟，还望指教

**Comment by hx1997** [comment]
没有反编译/反汇编功能，要反汇编左转楼上上的 repo 或者 https://gitee.com/openharmony/arkcompiler_runtime_core/tree/master#%E5%8F%8D%E6%B1%87%E7%BC%96%E5%99%A8%E5%B7%A5%E5%85%B7%E6%A6%82%E8%BF%B0
